In [1]:
# importing libraries
import pandas as pd
import numpy as np
import pymysql

In [2]:
from datetime import datetime

Convert CSV to DataFrame

In [3]:
df_buses_2=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Aassam_bus_details.csv")
df_buses_1=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\AndhraPradesh_bus_details.csv")
df_buses_3=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Bihar_bus_details.csv")
df_buses_4=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Chandigarh_bus_details.csv")
df_buses_5=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\HimachalPradesh_bus_details.csv")
df_buses_6=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Kadamba_bus_details.csv")
df_buses_7=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Meghalaya_bus_details.csv")
df_buses_8=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Kerala_bus_details.csv")
df_buses_9=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Punjab_bus_details.csv")
df_buses_10=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Rajasthan_bus_details.csv")
df_buses_11=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Sikkim_bus_details.csv")
df_buses_12=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Telangana_bus_details.csv")
df_buses_13=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\UttarPradhesh_bus_details.csv")
df_buses_14=pd.read_csv(r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\WestBengal_bus_details.csv")

In [4]:
# Getting data into DataFrame
Final_df=pd.concat([df_buses_1,df_buses_2,df_buses_3,df_buses_4,df_buses_5,df_buses_6,df_buses_7,df_buses_8,df_buses_9,df_buses_10,df_buses_11,df_buses_12,df_buses_13,df_buses_14],ignore_index=True)

In [5]:
Final_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3962,INDRA(A.C. Seater),20:40,07h 35m,04:15,3.7,INR 528,33 Seats available
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4900,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:40,08h 00m,04:40,3.6,INR 436,23 Seats available
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 95703,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:45,06h 45m,03:30,3.3,INR 452,18 Seats available
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3697,STAR LINER(NON-AC SLEEPER 2+1),20:45,07h 00m,03:45,3.9,INR 607,11 Seats available
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35212,STAR LINER(NON-AC SLEEPER 2+1),20:45,07h 00m,03:45,3.9,INR 565,11 Seats available
...,...,...,...,...,...,...,...,...,...,...
11092,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:35,Non AC Seater (2+3),05:35,03h 20m,08:55,4.7,INR 130,43 Seats available
11093,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55,03h 50m,10:45,4.2,INR 130,45 Seats available
11094,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45,03h 55m,16:40,4.2,INR 130,46 Seats available
11095,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Habra-Midnapur - 194|15:40,Non AC Seater (2+3),15:40,03h 00m,18:40,3.8,INR 111,35 Seats available
11096,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Barasat-Midnapur - 208|17:00,Non AC Seater (2+3),17:00,02h 00m,19:00,4.0,INR 111,37 Seats available

In [6]:
# Undersytand the datatypes and other elements of DataFrame
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11097 entries, 0 to 11096
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         11097 non-null  object
 1   Route_Link         11097 non-null  object
 2   Bus_Name           10947 non-null  object
 3   Bus_Type           10942 non-null  object
 4   Departing_Time     10947 non-null  object
 5   Duration           10947 non-null  object
 6   Reaching_Time      10947 non-null  object
 7   Star_Rating        10947 non-null  float64
 8   Price              10947 non-null  object
 9   Seat_Availability  10945 non-null  object
dtypes: float64(1), object(9)
memory usage: 867.1+ KB

# DATA CLEANING

In [7]:
print(Final_df[['Departing_Time','Reaching_Time']])

      Departing_Time Reaching_Time
0              20:40         04:15
1              20:40         04:40
2              20:45         03:30
3              20:45         03:45
4              20:45         03:45
...              ...           ...
11092          05:35         08:55
11093          06:55         10:45
11094          12:45         16:40
11095          15:40         18:40
11096          17:00         19:00

[11097 rows x 2 columns]

In [8]:
# Attempt to replace non values, if any
Final_df=Final_df.replace({np.nan: None})

In [9]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11097 entries, 0 to 11096
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         11097 non-null  object
 1   Route_Link         11097 non-null  object
 2   Bus_Name           10947 non-null  object
 3   Bus_Type           10942 non-null  object
 4   Departing_Time     10947 non-null  object
 5   Duration           10947 non-null  object
 6   Reaching_Time      10947 non-null  object
 7   Star_Rating        10947 non-null  object
 8   Price              10947 non-null  object
 9   Seat_Availability  10945 non-null  object
dtypes: object(10)
memory usage: 867.1+ KB

In [10]:
# Attempt to drop rows with NaN values
Final_df=Final_df.dropna()

In [11]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10941 entries, 0 to 11096
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         10941 non-null  object
 1   Route_Link         10941 non-null  object
 2   Bus_Name           10941 non-null  object
 3   Bus_Type           10941 non-null  object
 4   Departing_Time     10941 non-null  object
 5   Duration           10941 non-null  object
 6   Reaching_Time      10941 non-null  object
 7   Star_Rating        10941 non-null  object
 8   Price              10941 non-null  object
 9   Seat_Availability  10941 non-null  object
dtypes: object(10)
memory usage: 940.2+ KB

In [12]:
# Attempt to Convert Price to a Numeric Value
Final_df["Price"]=Final_df["Price"].str.replace("INR","")
Final_df["Price"]=Final_df["Price"].astype(float)
Final_df["Price"].fillna(0)

0        528.0
1        436.0
2        452.0
3        607.0
4        565.0
         ...
11092    130.0
11093    130.0
11094    130.0
11095    111.0
11096    111.0
Name: Price, Length: 10941, dtype: float64

In [13]:
Final_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3962,INDRA(A.C. Seater),20:40,07h 35m,04:15,3.7,528.0,33 Seats available
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4900,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:40,08h 00m,04:40,3.6,436.0,23 Seats available
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 95703,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:45,06h 45m,03:30,3.3,452.0,18 Seats available
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3697,STAR LINER(NON-AC SLEEPER 2+1),20:45,07h 00m,03:45,3.9,607.0,11 Seats available
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35212,STAR LINER(NON-AC SLEEPER 2+1),20:45,07h 00m,03:45,3.9,565.0,11 Seats available
...,...,...,...,...,...,...,...,...,...,...
11092,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:35,Non AC Seater (2+3),05:35,03h 20m,08:55,4.7,130.0,43 Seats available
11093,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55,03h 50m,10:45,4.2,130.0,45 Seats available
11094,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45,03h 55m,16:40,4.2,130.0,46 Seats available
11095,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Habra-Midnapur - 194|15:40,Non AC Seater (2+3),15:40,03h 00m,18:40,3.8,111.0,35 Seats available
11096,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Barasat-Midnapur - 208|17:00,Non AC Seater (2+3),17:00,02h 00m,19:00,4.0,111.0,37 Seats available

In [14]:
# Attempt to Covert Seats_Availbility to a numeric value
Final_df["Seat_Availability"]=Final_df["Seat_Availability"].str.replace("Seats available","")
Final_df["Seat_Availability"]=Final_df["Seat_Availability"].str.replace("Seat available","")
Final_df["Seat_Availability"]=Final_df["Seat_Availability"].astype(float)
Final_df["Seat_Availability"].fillna(0)

0        33.0
1        23.0
2        18.0
3        11.0
4        11.0
         ...
11092    43.0
11093    45.0
11094    46.0
11095    35.0
11096    37.0
Name: Seat_Availability, Length: 10941, dtype: float64

In [15]:
Final_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3962,INDRA(A.C. Seater),20:40,07h 35m,04:15,3.7,528.0,33.0
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4900,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:40,08h 00m,04:40,3.6,436.0,23.0
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 95703,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:45,06h 45m,03:30,3.3,452.0,18.0
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3697,STAR LINER(NON-AC SLEEPER 2+1),20:45,07h 00m,03:45,3.9,607.0,11.0
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35212,STAR LINER(NON-AC SLEEPER 2+1),20:45,07h 00m,03:45,3.9,565.0,11.0
...,...,...,...,...,...,...,...,...,...,...
11092,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:35,Non AC Seater (2+3),05:35,03h 20m,08:55,4.7,130.0,43.0
11093,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55,03h 50m,10:45,4.2,130.0,45.0
11094,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45,03h 55m,16:40,4.2,130.0,46.0
11095,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Habra-Midnapur - 194|15:40,Non AC Seater (2+3),15:40,03h 00m,18:40,3.8,111.0,35.0
11096,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Barasat-Midnapur - 208|17:00,Non AC Seater (2+3),17:00,02h 00m,19:00,4.0,111.0,37.0

In [16]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10941 entries, 0 to 11096
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         10941 non-null  object
 1   Route_Link         10941 non-null  object
 2   Bus_Name           10941 non-null  object
 3   Bus_Type           10941 non-null  object
 4   Departing_Time     10941 non-null  object
 5   Duration           10941 non-null  object
 6   Reaching_Time      10941 non-null  object
 7   Star_Rating        10941 non-null  object
 8   Price              10941 non-null  float64
 9   Seat_Availability  10941 non-null  float64
dtypes: float64(2), object(8)
memory usage: 940.2+ KB

In [17]:
Final_df["Star_Rating"].fillna(0,inplace=True)
Final_df["Bus_Name"].fillna("Not Available",inplace=True) 
Final_df["Bus_Type"].fillna("Not Available",inplace=True)

C:\Users\VIVEK - PC\AppData\Local\Temp\ipykernel_12276\3799071647.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_df["Star_Rating"].fillna(0,inplace=True)
C:\Users\VIVEK - PC\AppData\Local\Temp\ipykernel_12276\3799071647.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_df["Bus_Name"].fillna("Not Available",inplace=True)
C:\Users\VIVEK - PC\AppData\Local\Temp\ipykernel_12276\3799071647.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  Final_df["Bus_Type"].fillna("Not Available",inplace=True)

In [18]:
Final_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3962,INDRA(A.C. Seater),20:40,07h 35m,04:15,3.7,528.0,33.0
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4900,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:40,08h 00m,04:40,3.6,436.0,23.0
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 95703,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:45,06h 45m,03:30,3.3,452.0,18.0
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3697,STAR LINER(NON-AC SLEEPER 2+1),20:45,07h 00m,03:45,3.9,607.0,11.0
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35212,STAR LINER(NON-AC SLEEPER 2+1),20:45,07h 00m,03:45,3.9,565.0,11.0
...,...,...,...,...,...,...,...,...,...,...
11092,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:35,Non AC Seater (2+3),05:35,03h 20m,08:55,4.7,130.0,43.0
11093,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55,03h 50m,10:45,4.2,130.0,45.0
11094,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45,03h 55m,16:40,4.2,130.0,46.0
11095,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Habra-Midnapur - 194|15:40,Non AC Seater (2+3),15:40,03h 00m,18:40,3.8,111.0,35.0
11096,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Barasat-Midnapur - 208|17:00,Non AC Seater (2+3),17:00,02h 00m,19:00,4.0,111.0,37.0

In [19]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10941 entries, 0 to 11096
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         10941 non-null  object
 1   Route_Link         10941 non-null  object
 2   Bus_Name           10941 non-null  object
 3   Bus_Type           10941 non-null  object
 4   Departing_Time     10941 non-null  object
 5   Duration           10941 non-null  object
 6   Reaching_Time      10941 non-null  object
 7   Star_Rating        10941 non-null  object
 8   Price              10941 non-null  float64
 9   Seat_Availability  10941 non-null  float64
dtypes: float64(2), object(8)
memory usage: 940.2+ KB

In [20]:
print(Final_df[['Departing_Time', 'Reaching_Time']].head(10))

  Departing_Time Reaching_Time
0          20:40         04:15
1          20:40         04:40
2          20:45         03:30
3          20:45         03:45
4          20:45         03:45
5          20:45         03:40
6          20:50         04:05
7          20:50         04:00
8          20:55         04:05
9          21:00         04:15

In [21]:
# Attemp to convert time from Oject to dt.time format
Final_df['Departing_Time'] = pd.to_datetime(Final_df['Departing_Time'], format='%H:%M').dt.time
Final_df['Reaching_Time'] = pd.to_datetime(Final_df['Reaching_Time'], format='%H:%M').dt.time

In [22]:
print(Final_df[['Departing_Time', 'Reaching_Time']].head(10))

  Departing_Time Reaching_Time
0       20:40:00      04:15:00
1       20:40:00      04:40:00
2       20:45:00      03:30:00
3       20:45:00      03:45:00
4       20:45:00      03:45:00
5       20:45:00      03:40:00
6       20:50:00      04:05:00
7       20:50:00      04:00:00
8       20:55:00      04:05:00
9       21:00:00      04:15:00

In [23]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10941 entries, 0 to 11096
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         10941 non-null  object
 1   Route_Link         10941 non-null  object
 2   Bus_Name           10941 non-null  object
 3   Bus_Type           10941 non-null  object
 4   Departing_Time     10941 non-null  object
 5   Duration           10941 non-null  object
 6   Reaching_Time      10941 non-null  object
 7   Star_Rating        10941 non-null  object
 8   Price              10941 non-null  float64
 9   Seat_Availability  10941 non-null  float64
dtypes: float64(2), object(8)
memory usage: 940.2+ KB

In [24]:
Final_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3962,INDRA(A.C. Seater),20:40:00,07h 35m,04:15:00,3.7,528.0,33.0
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4900,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:40:00,08h 00m,04:40:00,3.6,436.0,23.0
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 95703,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:45:00,06h 45m,03:30:00,3.3,452.0,18.0
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3697,STAR LINER(NON-AC SLEEPER 2+1),20:45:00,07h 00m,03:45:00,3.9,607.0,11.0
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35212,STAR LINER(NON-AC SLEEPER 2+1),20:45:00,07h 00m,03:45:00,3.9,565.0,11.0
...,...,...,...,...,...,...,...,...,...,...
11092,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:35,Non AC Seater (2+3),05:35:00,03h 20m,08:55:00,4.7,130.0,43.0
11093,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55:00,03h 50m,10:45:00,4.2,130.0,45.0
11094,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45:00,03h 55m,16:40:00,4.2,130.0,46.0
11095,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Habra-Midnapur - 194|15:40,Non AC Seater (2+3),15:40:00,03h 00m,18:40:00,3.8,111.0,35.0
11096,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Barasat-Midnapur - 208|17:00,Non AC Seater (2+3),17:00:00,02h 00m,19:00:00,4.0,111.0,37.0

# SQL CONNECTION & DATABASE

In [44]:
# Creating SQL connection and Database
conn=pymysql.connect(host="localhost", user="root", password="Msd89_rhn", database="redbus")
my_cursor = conn.cursor()
my_cursor.execute("CREATE DATABASE IF NOT EXISTS redbus")

1

In [48]:
# Table Creation
my_cursor.execute('''CREATE TABLE IF NOT EXISTS bus_routes_(
                    ID INT AUTO_INCREMENT PRIMARY KEY, 
                    Route_Name VARCHAR(255) NULL,
                    Route_Link VARCHAR(255) NULL,
                    Bus_Name VARCHAR(255) NULL,
                    Bus_Type VARCHAR(255) NULL,
                    Departing_Time VARCHAR(100) NOT NULL,
                    Duration VARCHAR(255) NULL,
                    Reaching_Time VARCHAR(100) NOT NULL,
                    Star_Rating FLOAT NULL,
                    Price DECIMAL(10, 2),
                    Seat_Availability INT(10)
                    )''')
print("Table Created Successfully")

Table Created Successfully

In [28]:
# Attempt to reconfirm NaN values are droped
Final_df = Final_df.dropna()

In [29]:
Final_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3962,INDRA(A.C. Seater),20:40:00,07h 35m,04:15:00,3.7,528.0,33.0
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4900,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:40:00,08h 00m,04:40:00,3.6,436.0,23.0
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 95703,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:45:00,06h 45m,03:30:00,3.3,452.0,18.0
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3697,STAR LINER(NON-AC SLEEPER 2+1),20:45:00,07h 00m,03:45:00,3.9,607.0,11.0
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35212,STAR LINER(NON-AC SLEEPER 2+1),20:45:00,07h 00m,03:45:00,3.9,565.0,11.0
...,...,...,...,...,...,...,...,...,...,...
11092,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:35,Non AC Seater (2+3),05:35:00,03h 20m,08:55:00,4.7,130.0,43.0
11093,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55:00,03h 50m,10:45:00,4.2,130.0,45.0
11094,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45:00,03h 55m,16:40:00,4.2,130.0,46.0
11095,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Habra-Midnapur - 194|15:40,Non AC Seater (2+3),15:40:00,03h 00m,18:40:00,3.8,111.0,35.0
11096,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Barasat-Midnapur - 208|17:00,Non AC Seater (2+3),17:00:00,02h 00m,19:00:00,4.0,111.0,37.0

In [30]:
# Function to change time format
import pandas as pd
from datetime import datetime, time

def convert_to_normal_time(time_24):
    if isinstance(time_24, str):
        # Split the time into hours and minutes
        hours, minutes = map(int, time_24.split(':'))
    elif isinstance(time_24, pd.Timestamp):
        # Extract hours and minutes from a pandas Timestamp
        hours = time_24.hour
        minutes = time_24.minute
    elif isinstance(time_24, time):
        # Extract hours and minutes from a datetime.time object
        hours = time_24.hour
        minutes = time_24.minute
    else:
        return None  # Handle cases where the input is not valid

    # Determine AM/PM and convert hours
    period = 'AM' if hours < 12 else 'PM'
    hours = hours % 12
    hours = 12 if hours == 0 else hours  # Convert 0 hours to 12
    
    return f"{hours:02}:{minutes:02} {period}"

In [31]:
# Attempt to change time to AM/PM period
Final_df['Departing_Time']=Final_df['Departing_Time'].apply(convert_to_normal_time)
Final_df['Reaching_Time']=Final_df['Reaching_Time'].apply(convert_to_normal_time)

In [32]:
Final_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3962,INDRA(A.C. Seater),08:40 PM,07h 35m,04:15 AM,3.7,528.0,33.0
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4900,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",08:40 PM,08h 00m,04:40 AM,3.6,436.0,23.0
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 95703,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",08:45 PM,06h 45m,03:30 AM,3.3,452.0,18.0
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3697,STAR LINER(NON-AC SLEEPER 2+1),08:45 PM,07h 00m,03:45 AM,3.9,607.0,11.0
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35212,STAR LINER(NON-AC SLEEPER 2+1),08:45 PM,07h 00m,03:45 AM,3.9,565.0,11.0
...,...,...,...,...,...,...,...,...,...,...
11092,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:35,Non AC Seater (2+3),05:35 AM,03h 20m,08:55 AM,4.7,130.0,43.0
11093,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55 AM,03h 50m,10:45 AM,4.2,130.0,45.0
11094,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45 PM,03h 55m,04:40 PM,4.2,130.0,46.0
11095,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Habra-Midnapur - 194|15:40,Non AC Seater (2+3),03:40 PM,03h 00m,06:40 PM,3.8,111.0,35.0
11096,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Barasat-Midnapur - 208|17:00,Non AC Seater (2+3),05:00 PM,02h 00m,07:00 PM,4.0,111.0,37.0

In [33]:
Final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10941 entries, 0 to 11096
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Route_Name         10941 non-null  object
 1   Route_Link         10941 non-null  object
 2   Bus_Name           10941 non-null  object
 3   Bus_Type           10941 non-null  object
 4   Departing_Time     10941 non-null  object
 5   Duration           10941 non-null  object
 6   Reaching_Time      10941 non-null  object
 7   Star_Rating        10941 non-null  object
 8   Price              10941 non-null  float64
 9   Seat_Availability  10941 non-null  float64
dtypes: float64(2), object(8)
memory usage: 940.2+ KB

In [52]:
# Convert DataFrame to CSV
path=r"D:\Education\Data Science\Project\Capstone_Projects\Redbus\Final_busroutedetails_df.csv"
Final_df.to_csv(path,index=False)

In [57]:
# Convert 'Departing_Time' to the correct format
Final_df['Departing_Time'] = pd.to_datetime(Final_df['Departing_Time']).dt.strftime('%H:%M:%S')
Final_df['Reaching_Time'] = pd.to_datetime(Final_df['Reaching_Time']).dt.strftime('%H:%M:%S')

C:\Users\VIVEK - PC\AppData\Local\Temp\ipykernel_12276\2131632955.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Final_df['Departing_Time'] = pd.to_datetime(Final_df['Departing_Time']).dt.strftime('%H:%M:%S')
C:\Users\VIVEK - PC\AppData\Local\Temp\ipykernel_12276\2131632955.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  Final_df['Reaching_Time'] = pd.to_datetime(Final_df['Reaching_Time']).dt.strftime('%H:%M:%S')

In [59]:
Final_df

,Route_Name,Route_Link,Bus_Name,Bus_Type,Departing_Time,Duration,Reaching_Time,Star_Rating,Price,Seat_Availability
0,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3962,INDRA(A.C. Seater),20:40:00,07h 35m,04:15:00,3.7,528.0,33.0
1,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 4900,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:40:00,08h 00m,04:40:00,3.6,436.0,23.0
2,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 95703,"SUPER LUXURY (NON-AC, 2 + 2 PUSH BACK)",20:45:00,06h 45m,03:30:00,3.3,452.0,18.0
3,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 3697,STAR LINER(NON-AC SLEEPER 2+1),20:45:00,07h 00m,03:45:00,3.9,607.0,11.0
4,Hyderabad to Vijayawada,https://www.redbus.in/bus-tickets/hyderabad-to...,APSRTC - 35212,STAR LINER(NON-AC SLEEPER 2+1),20:45:00,07h 00m,03:45:00,3.9,565.0,11.0
...,...,...,...,...,...,...,...,...,...,...
11092,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|05:35,Non AC Seater (2+3),05:35:00,03h 20m,08:55:00,4.7,130.0,43.0
11093,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|06:55,Non AC Seater (2+3),06:55:00,03h 50m,10:45:00,4.2,130.0,45.0
11094,Habra to Heria,https://www.redbus.in/bus-tickets/habra-to-heria,WBTC (CTC) HABRA-DIGHA via Bally - 26|12:45,Non AC Seater (2+3),12:45:00,03h 55m,16:40:00,4.2,130.0,46.0
11095,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Habra-Midnapur - 194|15:40,Non AC Seater (2+3),15:40:00,03h 00m,18:40:00,3.8,111.0,35.0
11096,Midnapore to Kolkata Airport,https://www.redbus.in/bus-tickets/midnapore-to...,WBTC (CTC) Barasat-Midnapur - 208|17:00,Non AC Seater (2+3),17:00:00,02h 00m,19:00:00,4.0,111.0,37.0

In [60]:
# SQL query to insert data into busroutes_details
insert_query = '''INSERT INTO bus_routes_(
                    Route_Name,
                    Route_Link,
                    Bus_Name,
                    Bus_Type,
                    Departing_Time,
                    Duration,
                    Reaching_Time,
                    Star_Rating,
                    Price,
                    Seat_Availability)
                VALUES(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)'''
data = Final_df.values.tolist()
my_cursor.executemany(insert_query, data)
conn.commit()

print("Values inserted successfully")

Values inserted successfully